
- name: Deploy a template to /etc/motd
  ansible.builtin.template:
    src: motd.j2
    dest: /etc/motd

- name: Customize prompt
  ansible.builtin.template:
    src: prompt.sh.j2
    dest: /etc/profile.d/custom-prompt.sh
    mode: '0755'
