- hosts: localhost
  connection: local
  gather_facts: no
  become: false
  tasks:
  - include_role:
      name: ../roles/enable-oadp-operator
  - include_role:
      name: ../roles/enable-oadp-object-storage
  - include_role:
      name: ../roles/restore-hub
