apiVersion: oadp.openshift.io/v1alpha1
kind: Velero
metadata:
  name: velero
  namespace: openshift-adp
spec:
  enableRestic: false
  defaultVeleroPlugins:
  - azure
  - openshift
  backupStorageLocations:
  - name: default
    default: true
    provider: azure
    credential:
      key: cloud
      name: cloud-credentials-azure
    objectStorage:
      bucket: aoc12-backup-restore-test
      prefix: backups
    config:
      resourceGroup: sdminone-aoc12-backup-rg
      storageAccount: sdminonnebackupsa
      subscriptionId: c7130a18-cbc9-4b44-9307-1f56446fb730
      storageAccountKeyEnvVar: AZURE_STORAGE_ACCOUNT_ACCESS_KEY
