---

- name: Create temporary SPOKE directory
  ansible.builtin.tempfile:
    state: directory
    suffix: spoke
  register: tempdir

- name: Generate the Import Blob
  shell: |-
    oc get secret {{ AKS_NAME }}-import -n {{ AKS_NAME }} -ojsonpath='{.data.crds\.yaml}' | base64 --decode > {{ tempdir.path }}/01_import.yaml
    oc get secret {{ AKS_NAME }}-import -n {{ AKS_NAME }} -ojsonpath='{.data.import\.yaml}' | base64 --decode > {{ tempdir.path }}/04_import.yaml

- name: Detaching managed cluster
  shell: |-
    oc delete managedcluster {{ AKS_NAME }}
  register: detach_out

- name: Switch to Managed Cluster and Delete Import Blob
  shell: |-
    IMPORT_BLOB=$(cat {{ tempdir.path }}/{{ item }} | base64 -w 0)
    az aks command invoke --resource-group {{ AKS_EFFECTIVE_MRG }} \
      --name {{ AKS_NAME }} \
      --subscription {{ AKS_SUB }} \
      --command "echo $IMPORT_BLOB | base64 --decode | kubectl delete -f -"
  with_items:
    - 01_import.yaml
    - 04_import.yaml
